### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rOluochKe**
Kindly review and share your feedback, thank you.

### CODE REVIEW

**Comment by ebukaume** [comment]
Hi @rOluochKe :v: 

You have done a nice job to this point. However, there are a few things missing out in this project.

- [ ] The project has a descriptive README.md. See [template](https://github.com/othneildrew/Best-README-Template) for guide.
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload and fix all errors.
- [ ] No `!important` overusing. See [this](https://speckyboy.com/good-bad-css-practices/) for the basic dos and don'ts of CSS usage.

And lastly, let's check why stickler-CI is failing. Are you using the correct [configuration](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml)? Please refer to [this repo](https://github.com/microverseinc/linters-config/tree/master/css) and be careful to follow the instructions correctly.

**Kindly submit another code review request as soon as you fix these issues.**

Happy Coding :man_dancing:

**Comment by rOluochKe** [comment]
Made all the changes

**Comment by rOluochKe** [comment]
all errors solved

**Comment by ebukaume** [comment]
Hi @rOluochKe :wave: 

Nice work so far. I see you have made the README more professional. You also removed all `!important` in your CSS. Thumbs up on those :+1: 

However, you seem to have missed out on some required points. Please kindly fix them and submit another code review form.

- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload and fix all errors.
- [ ] Stickler-CI fails to run, still. Please sure you set things up correctly and refer to [here](https://github.com/microverseinc/linters-config/tree/master/css#troubleshooting) for troubleshooting guides.

[Note] Don't forget to use a more descriptive commit and PR messages from now on, please; it is important!

**@rOluochKe, kindly fix those and submit another review request.**

**Happy coding :v:**

**Comment by rOluochKe** [comment]
Hey,

I have solved the following as required by the tse:
 Check HTML markup with this validator
 The project has a descriptive README.md
 No !important overusing

**Comment by rOluochKe** [comment]
all linting errors are solved

**Pull request merged**
